sudo: required
services:
  - docker

before_install:
  - docker build -t yanlongsun/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true yanlongsun/react-test npm test

after_success: 
  - docker build -t yanlongsun/multi-client ./client
  - docker build -t yanlongsun/multi-nginx ./nginx
  - docker build -t yanlongsun/multi-server ./server
  - docker build -t yanlongsun/multi-worker ./worker

